const keys = ['averageDays','diaryCoverage','availableNow','overBudget','periodRemaining','budgetGoal','activityPeriod','stepCoverage','baseBudget','stepBonus','recordedFood','walkingEstimate','historyCoverageNote','historyFailed','eatenToday','periodEaten'];
const words = {
  en: ['Daily average · {{days}} days','Logged: {{n}}/{{total}} days','Available now','Over the goal','Period balance','Goal: {{n}} kcal','Steps in this period','Step data: {{n}}/{{total}} days','Base goal','Extra from steps','Food logged','Walking estimate','History starts with measurements on this phone. Missing days are not counted as zero.','Could not save or load step history.','Eaten today: {{n}} kcal','Eaten in period: {{n}} kcal'],
  ru: ['Среднее/день · {{days}} дней','Заполнено {{n}} из {{total}} дней','Можно сейчас','Сверх нормы','Остаток за период','Норма: {{n}} ккал','Шаги за период','Есть шаги: {{n}} из {{total}} дней','Базовая норма','Добавка за шаги','Записано еды','Оценка ходьбы','История начинается с измерений на этом телефоне. Пропуски не считаем нулевыми шагами.','Не удалось сохранить или загрузить историю шагов.','Съедено сегодня: {{n}} ккал','Съедено за период: {{n}} ккал'],
  uk: ['Середнє/день · {{days}} днів','Заповнено {{n}} із {{total}} днів','Можна зараз','Понад норму','Залишок за період','Норма: {{n}} ккал','Кроки за період','Є кроки: {{n}} із {{total}} днів','Базова норма','Додаток за кроки','Записано їжі','Оцінка ходьби','Історія починається з вимірювань на цьому телефоні. Пропуски не вважаємо нульовими кроками.','Не вдалося зберегти чи завантажити історію кроків.','З’їдено сьогодні: {{n}} ккал','З’їдено за період: {{n}} ккал'],
  es: ['Media diaria · {{days}} días','Registrados: {{n}}/{{total}} días','Disponible ahora','Sobre el objetivo','Saldo del período','Objetivo: {{n}} kcal','Pasos del período','Datos: {{n}}/{{total}} días','Objetivo base','Extra por pasos','Comida registrada','Estimación al caminar','El historial comienza con las mediciones de este teléfono. Los días sin datos no son cero pasos.','No se pudo guardar o cargar el historial.','Consumido hoy: {{n}} kcal','Consumido en el período: {{n}} kcal'],
  de: ['Tagesmittel · {{days}} Tage','Erfasst: {{n}}/{{total}} Tage','Jetzt verfügbar','Über dem Ziel','Bilanz im Zeitraum','Ziel: {{n}} kcal','Schritte im Zeitraum','Daten: {{n}}/{{total}} Tage','Basisziel','Schrittbonus','Erfasstes Essen','Gehschätzung','Verlauf ab Messungen auf diesem Telefon. Fehlende Tage bedeuten nicht null Schritte.','Schrittverlauf konnte nicht gespeichert oder geladen werden.','Heute gegessen: {{n}} kcal','Im Zeitraum gegessen: {{n}} kcal'],
  pl: ['Średnio/dzień · {{days}} dni','Zapisano: {{n}}/{{total}} dni','Dostępne teraz','Ponad cel','Bilans okresu','Cel: {{n}} kcal','Kroki w okresie','Dane: {{n}}/{{total}} dni','Cel bazowy','Dodatek za kroki','Zapisane jedzenie','Szacunek chodzenia','Historia od pomiarów na tym telefonie. Brak danych nie oznacza zera kroków.','Nie udało się zapisać lub wczytać historii.','Zjedzono dziś: {{n}} kcal','Zjedzono w okresie: {{n}} kcal'],
  ja: ['1日平均 · {{days}}日間','記録：{{n}}/{{total}}日','今食べられる目安','目標超過','期間の残り','目標：{{n}} kcal','期間の歩数','歩数記録：{{n}}/{{total}}日','基本目標','歩数による追加','食事記録','歩行の推定','この端末での測定から履歴が始まります。欠測日はゼロ歩として数えません。','歩数履歴を保存または読み込めませんでした。','今日の摂取：{{n}} kcal','期間の摂取：{{n}} kcal'],
  zh: ['日均 · {{days}}天','已记：{{n}}/{{total}}天','当前可用','超过目标','期间余额','目标：{{n}} 千卡','期间步数','步数记录：{{n}}/{{total}}天','基础目标','步数增加','已记饮食','步行估算','历史从此手机的测量开始。缺失日期不视为零步数。','无法保存或读取步数历史。','今日已摄入：{{n}} 千卡','期间已摄入：{{n}} 千卡'],
};
export const activityTranslations = Object.fromEntries(Object.entries(words).map(([lang, values]) => [lang, Object.fromEntries(keys.map((key, i) => ['x_' + key, values[i]]))]));
