const keys = ['above','available','details','of','current','formula','history'];
const words = {
  ru: ['Выше лимита','Можно ещё','Как рассчитан лимит','из {{n}} ккал','Текущий лимит','Лимит = базовая норма с учётом цели + учтённая добавка за шаги. Остаток = лимит − записанная еда. Это оценка, не медицинская рекомендация.','Среднее считается по дням с записями и показано для справки: оно не меняет лимит. Пропуски не считаются нулевым потреблением.'],
  uk: ['Понад ліміт','Можна ще','Як розраховано ліміт','із {{n}} ккал','Поточний ліміт','Ліміт = базова норма з урахуванням мети + врахований додаток за кроки. Залишок = ліміт − записана їжа. Це оцінка, не медична рекомендація.','Середнє враховує дні із записами та наведене для довідки: воно не змінює ліміт. Пропуски не означають нульове споживання.'],
  en: ['Above the limit','Still available','How the limit is calculated','of {{n}} kcal','Current limit','Limit = base goal including your weight goal + eligible step credit. Remaining = limit − logged food. This is an estimate, not medical advice.','Averages use logged days only and are informational: they do not change the limit. Missing entries do not mean zero intake.'],
  es: ['Sobre el límite','Disponible','Cómo se calcula el límite','de {{n}} kcal','Límite actual','Límite = objetivo base + ajuste válido por pasos. Disponible = límite − comida registrada. Es una estimación, no consejo médico.','La media usa solo días registrados y no modifica el límite. Los días sin datos no significan consumo cero.'],
  de: ['Über dem Limit','Noch verfügbar','So wird das Limit berechnet','von {{n}} kcal','Aktuelles Limit','Limit = Basisziel + anrechenbarer Schrittbonus. Rest = Limit − erfasstes Essen. Eine Schätzung, keine medizinische Empfehlung.','Der Durchschnitt nutzt nur erfasste Tage und ändert das Limit nicht. Fehlende Einträge bedeuten nicht null Verzehr.'],
  pl: ['Powyżej limitu','Jeszcze dostępne','Jak obliczamy limit','z {{n}} kcal','Aktualny limit','Limit = cel bazowy + uwzględniony dodatek za kroki. Pozostało = limit − zapisane jedzenie. To szacunek, nie porada medyczna.','Średnia obejmuje dni z zapisami i nie zmienia limitu. Brak wpisu nie oznacza zerowego spożycia.'],
  ja: ['上限超過','あと食べられる目安','上限の計算方法','上限 {{n}} kcal','現在の上限','上限＝基本目標＋対象の歩数による追加分。残り＝上限−記録した食事。推定値であり、医療上の助言ではありません。','平均は記録のある日のみで計算し、上限には影響しません。記録がない日は摂取ゼロとはみなしません。'],
  zh: ['超过限额','当前剩余','限额如何计算','共 {{n}} 千卡','当前限额','限额＝基础目标＋符合条件的步数增加量。剩余＝限额−已记录饮食。这是估算，并非医疗建议。','平均值仅使用有记录的日期，不会改变限额。缺少记录不代表摄入为零。'],
};
export const budgetTranslations = Object.fromEntries(Object.entries(words).map(([lang, values]) => [lang, Object.fromEntries(keys.map((key, i) => ['b_' + key, values[i]]))]));
