const keys=['automatic','saveMode','average','averageHint','sync','wait','privacy','connect','rotate','rotateConfirm','revoke','revokeConfirm','copyUrl','copyKey','copied','copyManual','keyOnce','headers','run','historyImport','check','expense','difference','active'];
const words={
  ru:['Автоматически','Изменения режима применятся после «Сохранить».','Средняя разница · {{days}} дней','Среднее = расход из Health − записанная еда за завершённые дни. Учитываются только дни с обоими видами данных. Плюс — расход больше еды, минус — еда больше расхода.','Последний импорт: {{time}}','Данные из Health Auto Export ещё не получены.','Передаются только дневные шаги, активные калории и расход в покое. История хранится на сервере Gramix до 33 дней, не отправляется в Telegram. Импорт не даёт доступа к дневнику.','Подключить Health Auto Export','Создать новый ключ','Старый ключ перестанет работать. Продолжить?','Отключить и удалить импорт','Отключить импорт и удалить его историю? Записи еды сохранятся.','Копировать URL','Копировать ключ','Скопировано','Скопируйте поле вручную.','Ключ показан только сейчас. Скопируйте его в приложение; не отправляйте в чат.','Вставьте URL. В HTTP Headers добавьте X-API-Key и скопированный ключ.','Включите автоматизацию и нажмите Manual Export на разблокированном iPhone.','Для среднего импортируйте прошлые 7 дней с теми же настройками. Не суммируйте отдельные источники. Фоновый запуск каждый час iOS не гарантирует.','Проверить импорт','Расход к этому моменту: {{n}} ккал','Расход − еда','Активность (без покоя)'],
  uk:['Автоматично','Зміни режиму застосуються після «Зберегти».','Середня різниця · {{days}} днів','Середнє = витрати з Health − записана їжа за завершені дні. Лише дні з обома видами даних. Плюс — витрати більші за їжу, мінус — їжа більша за витрати.','Останній імпорт: {{time}}','Дані з Health Auto Export ще не отримано.','Передаються лише денні кроки, активні калорії та витрати у спокої. Історія зберігається на сервері Gramix до 33 днів, не надсилається в Telegram. Імпорт не дає доступу до щоденника.','Підключити Health Auto Export','Створити новий ключ','Старий ключ перестане працювати. Продовжити?','Відключити й видалити імпорт','Відключити імпорт і видалити його історію? Записи їжі залишаться.','Копіювати URL','Копіювати ключ','Скопійовано','Скопіюйте поле вручну.','Ключ показано лише зараз. Скопіюйте його в застосунок; не надсилайте в чат.','Вставте URL. У HTTP Headers додайте X-API-Key і скопійований ключ.','Увімкніть автоматизацію та натисніть Manual Export на розблокованому iPhone.','Для середнього імпортуйте минулі 7 днів із такими ж параметрами. Не додавайте окремі джерела. Фоновий запуск щогодини iOS не гарантує.','Перевірити імпорт','Витрати до цього моменту: {{n}} ккал','Витрати − їжа','Активність (без спокою)'],
  en:['Automatic','Mode changes apply after Save.','Average difference · {{days}} days','Average = Health expenditure − logged food on completed days with both data types. Positive: expenditure exceeds food; negative: food exceeds expenditure.','Last import: {{time}}','No Health Auto Export data received yet.','Only daily steps, active energy and resting energy are imported. Stored on Gramix servers for up to 33 days, never sent to Telegram. The import key cannot read your diary.','Connect Health Auto Export','Create new key','The old key will stop working. Continue?','Disconnect and delete imports','Delete imported history and revoke access? Food entries remain.','Copy URL','Copy key','Copied','Copy the field manually.','Key shown only now. Copy it into the app; never share it in chat.','Paste the URL. Add HTTP Header X-API-Key with the copied key.','Enable automation and tap Manual Export on an unlocked iPhone.','Import the previous 7 days with the same settings for averages. Do not sum individual sources. iOS cannot guarantee hourly background runs.','Check import','Expenditure so far: {{n}} kcal','Expenditure − food','Activity (net of rest)']
};
export const healthTranslations=Object.fromEntries(Object.entries(words).map(([lang,values])=>[lang,Object.fromEntries(keys.map((key,i)=>['h_'+key,values[i]]))]));
for(const [lang,values] of Object.entries({
  ru:['Как рассчитано','Разница = расчётный расход в покое с полуночи + полученные активные калории (либо оценка по шагам) − записанная еда. Это оценка, не требование ждать или отрабатывать еду.'],
  uk:['Як розраховано','Різниця = розрахункові витрати у спокої від опівночі + отримані активні калорії (або оцінка за кроками) − записана їжа. Це оцінка, не вимога чекати чи відпрацьовувати їжу.'],
  en:['How it is calculated','Difference = estimated rest since midnight + imported active energy (or a step estimate) − logged food. An estimate, not a requirement to wait or earn food.']
})) Object.assign(healthTranslations[lang],{h_how:values[0],h_formula:values[1]});
for (const [lang, values] of Object.entries({
  uk: ['Середні витрати за день · {{days}} днів', 'Спокій + активність. Їжа не віднімається. Беремо завершені дні з даними; якщо немає калорій Health, оцінюємо спокій за поточним профілем, а ходьбу — за кроками. Це орієнтир, не ліміт харчування.', 'Оцінка · спокій + активність', 'Днів з даними: {{n}} із {{total}}'],
  ru: ['Средний расход за день · {{days}} дней', 'Покой + активность. Еда не вычитается. Учитываем завершённые дни с данными; без калорий Health оцениваем покой по текущему профилю, а ходьбу — по шагам. Это ориентир, не лимит питания.', 'Оценка · покой + активность', 'Дней с данными: {{n}} из {{total}}'],
  en: ['Average daily expenditure · {{days}} days', 'Rest + activity, without subtracting food. Uses completed days with data. Missing Health energy is estimated from your current profile for rest and steps for walking. A guide, not a food limit.', 'Estimate · rest + activity', 'Days with data: {{n}} of {{total}}'],
})) Object.assign(healthTranslations[lang], {h_average:values[0], h_averageHint:values[1], h_estimated:values[2], h_coverage:values[3]});
const activityLabels = {
  uk: ['З’їдено / витрачено', 'З’їдено / денна норма', 'Їжа перевищує витрати на', 'Витрати перевищують їжу на', 'Їжа й витрати зрівнялися', 'Оцінка на зараз · не вимога відпрацьовувати їжу', 'Оцінка лише за кроками: велосипед та інші тренування без активних калорій не враховані.', 'Активні калорії з підключеного сервісу: включають передані ним тренування, без повторного додавання кроків.', 'Даних активності немає. Це не означає нульові витрати.', 'В автоматичному режимі Active Energy враховує також велосипед та інші тренування, якщо їхній застосунок записує активні калорії у Здоров’я. Експорт тренувань окремо не потрібний. Самі кроки велосипед не визначають.', 'Кроки й активні калорії', 'Дозволити калорії тренувань', 'Увімкніть «Автоматично» та збережіть профіль, щоб враховувати активні калорії.', 'Активні калорії не отримано. Перевірте дозвіл і запис тренувань у Health Connect.', 'Health Connect передає загальні активні калорії, включно з велосипедом, якщо джерело їх записало. Дані залишаються на телефоні.'],
  ru: ['Съедено / потрачено', 'Съедено / дневная норма', 'Еда превышает расход на', 'Расход превышает еду на', 'Еда и расход сравнялись', 'Оценка сейчас · не требование отрабатывать еду', 'Оценка только по шагам: велосипед и другие тренировки без активных калорий не учтены.', 'Активные калории из подключённого сервиса: включают переданные им тренировки без повторного добавления шагов.', 'Данных активности нет. Это не означает нулевой расход.', 'В автоматическом режиме Active Energy учитывает велосипед и другие тренировки, если их приложение записывает активные калории в Здоровье. Отдельный экспорт тренировок не нужен. По шагам велосипед не определить.', 'Шаги и активные калории', 'Разрешить калории тренировок', 'Выберите «Автоматически» и сохраните профиль для учёта активных калорий.', 'Активные калории не получены. Проверьте разрешение и запись тренировок в Health Connect.', 'Health Connect передаёт общие активные калории, включая велосипед, если источник их записал. Данные остаются на телефоне.'],
  en: ['Eaten / expended', 'Eaten / daily goal', 'Food exceeds expenditure by', 'Expenditure exceeds food by', 'Food and expenditure match', 'Estimate so far · no need to earn food', 'Steps-only estimate: cycling and other workouts without active energy are not included.', 'Active energy from the connected service includes workouts it reports; steps are not added again.', 'Activity data is missing, not zero expenditure.', 'In Automatic mode, Active Energy includes cycling and other workouts when their app writes active energy to Apple Health. Separate workout export is not needed. Steps alone cannot detect cycling.', 'Steps and active energy', 'Allow workout calories', 'Select Automatic and save your profile to use active energy.', 'Active energy has not been received. Check permission and workout data in Health Connect.', 'Health Connect supplies total active energy, including cycling when the source records it. Data stays on this phone.'],
};
const activityKeys=['eatenSpent','eatenGoal','foodAhead','spentAhead','even','balanceHint','walkingOnly','allActivity','noActivity','sportImport','activityConnect','allowEnergy','selectAuto','energyMissing','nativeSport'];
for (const [lang, values] of Object.entries(activityLabels)) Object.assign(healthTranslations[lang], Object.fromEntries(activityKeys.map((key,i)=>['h_'+key,values[i]])));
